# Generated by Django 3.0.8 on 2022-07-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ambulanceModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('book', models.BooleanField(default=False)),
                ('title', models.CharField(default='Ambulance', max_length=50)),
                ('dis', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
